name: Build qBittorrent-Enhanced-Edition nevinee

on:
    release:
        types: [published]

jobs:
  build1:
    name: none
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          qbitorrent_tag=$(echo ${GITHUB_REF:10} | cut -f 1 -d "_")
          QBEE_TAG=$(echo ${GITHUB_REF:10} | cut -f 2 -d "_")
          echo "::set-output name=qbitorrent_tag::${qbitorrent_tag}"
          echo "::set-output name=QBEE_TAG::${QBEE_TAG}"
          echo "::set-output name=version::${QBEE_TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: nevinee.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            qbitorrent_tag=${{ steps.set-version.outputs.qbitorrent_tag }}
            QBEE_TAG=${{ steps.set-version.outputs.QBEE_TAG }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:${{ steps.set-version.outputs.version }}
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:latest_nevinee

  build2:
    name: iyuu
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          qbitorrent_tag=$(echo ${GITHUB_REF:10} | cut -f 1 -d "_")
          QBEE_TAG=$(echo ${GITHUB_REF:10} | cut -f 2 -d "_")
          echo "::set-output name=qbitorrent_tag::${qbitorrent_tag}"
          echo "::set-output name=QBEE_TAG::${QBEE_TAG}"
          echo "::set-output name=version::${QBEE_TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: nevinee.iyuu.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            qbitorrent_tag=${{ steps.set-version.outputs.qbitorrent_tag }}
            QBEE_TAG=${{ steps.set-version.outputs.QBEE_TAG }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:${{ steps.set-version.outputs.version }}-iyuu
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:latest_nevinee-iyuu

  job1:
    needs: [build1, build2]
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/qbittorrentee
          short-description: 由 nevinee 大佬的 qBittorrent 镜像改编的 qBittorrent Enhanced Edition 镜像
          readme-filepath: ./README.md
