name: Build & Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - info.json

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Set Version
        id: set-version
        run: |
          VERSION_GET=$(jq -r '.[0].build' info.json)

          QBEE_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_enhanced_edition_version" info.json | sed 's/v//')
          QB_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_version" info.json | sed 's/v//')

          echo "QB_TAG=${QB_TAG}" >> $GITHUB_OUTPUT
          echo "QBEE_TAG=${QBEE_TAG}" >> $GITHUB_OUTPUT

          curl -L \
            -o qbittorrent_enhanced_qt6_x64_setup.exe \
            https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${QBEE_TAG}/qbittorrent_enhanced_${QBEE_TAG}_qt6_x64_setup.exe
          curl -L \
            -o qbittorrent_enhanced_x64_setup.exe \
            https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${QBEE_TAG}/qbittorrent_enhanced_${QBEE_TAG}_x64_setup.exe
          curl -L \
            -o qbittorrent_enhanced_setup.exe \
            https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${QBEE_TAG}/qbittorrent_enhanced_${QBEE_TAG}_setup.exe

      -
        name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set-version.outputs.QB_TAG }}-${{ steps.set-version.outputs.QBEE_TAG }}
          name: ${{ steps.set-version.outputs.QB_TAG }}-${{ steps.set-version.outputs.QBEE_TAG }}
          body: qBittorrent-Enhanced-Edition v${{ steps.set-version.outputs.QBEE_TAG }}
          draft: false
          prerelease: false
          files: |
            qbittorrent_enhanced_qt6_x64_setup.exe
            qbittorrent_enhanced_x64_setup.exe
            qbittorrent_enhanced_setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build1:
    name: none
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          VERSION_GET=$(jq -r '.[0].build' info.json)

          QBEE_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_enhanced_edition_version" info.json | sed 's/v//')
          QB_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_version" info.json | sed 's/v//')
          AMD64_NAME=$(jq -r ".[${VERSION_GET}].arch.amd64.file_name" info.json)
          ARM64V8_NAME=$(jq -r ".[${VERSION_GET}].arch.arm64v8.file_name" info.json)
          ARMV7_NAME=$(jq -r ".[${VERSION_GET}].arch.armv7.file_name" info.json)

          echo "QB_TAG=${QB_TAG}" >> $GITHUB_OUTPUT
          echo "QBEE_TAG=${QBEE_TAG}" >> $GITHUB_OUTPUT
          echo "AMD64_NAME=${AMD64_NAME}" >> $GITHUB_OUTPUT
          echo "ARM64V8_NAME=${ARM64V8_NAME}" >> $GITHUB_OUTPUT
          echo "ARMV7_NAME=${ARMV7_NAME}" >> $GITHUB_OUTPUT

          git clone -b master https://github.com/devome/dockerfiles.git files
          cp -r files/qbittorrent/root root
          cp -r files/qbittorrent/root2 root2
          ls -al
          ls -al root
          ls -al root2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/qbittorrentee
          tags: |
            type=raw,value=${{ steps.set-version.outputs.QB_TAG }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: nevinee.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            QBEE_TAG=${{ steps.set-version.outputs.QBEE_TAG }}
            AMD64_NAME=${{ steps.set-version.outputs.AMD64_NAME }}
            ARM64V8_NAME=${{ steps.set-version.outputs.ARM64V8_NAME }}
            ARMV7_NAME=${{ steps.set-version.outputs.ARMV7_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

  build2:
    name: iyuu
    needs: [build1]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          VERSION_GET=$(jq -r '.[0].build' info.json)
          QB_TAG=$(jq -r ".[${VERSION_GET}].qbittorrent_version" info.json | sed 's/v//')
          echo "QB_TAG=${QB_TAG}" >> $GITHUB_OUTPUT

          git clone -b master https://github.com/devome/dockerfiles.git files
          cp -r files/qbittorrent/root root
          cp -r files/qbittorrent/root2 root2
          ls -al
          ls -al root
          ls -al root2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/qbittorrentee
          tags: |
            type=raw,value=${{ steps.set-version.outputs.QB_TAG }}-iyuu
            type=raw,value=latest-iyuu

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: nevinee.iyuu.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            QB_TAG=${{ steps.set-version.outputs.QB_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
