name: Build qBittorrent-Enhanced-Edition nevinee

on:
    release:
        types: [published]

jobs:
  build1:
    name: none
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          QB_TAG=$(echo ${GITHUB_REF:10} | cut -f 1 -d "_")
          QBEE_TAG=$(echo ${GITHUB_REF:10} | cut -f 2 -d "_")
          echo "QB_TAG=${QB_TAG}" >> $GITHUB_OUTPUT
          echo "QBEE_TAG=${QBEE_TAG}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.set-version.outputs.QBEE_TAG }}
          file: ./${{ steps.set-version.outputs.QBEE_TAG }}/nevinee.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            qbitorrent_tag=${{ steps.set-version.outputs.QB_TAG }}
            QBEE_TAG=${{ steps.set-version.outputs.QBEE_TAG }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:${{ steps.set-version.outputs.QB_TAG }}
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:latest

  build2:
    name: iyuu
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          QB_TAG=$(echo ${GITHUB_REF:10} | cut -f 1 -d "_")
          QBEE_TAG=$(echo ${GITHUB_REF:10} | cut -f 2 -d "_")
          echo "QB_TAG=${QB_TAG}" >> $GITHUB_OUTPUT
          echo "QBEE_TAG=${QBEE_TAG}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v4
        with:
          context: ./${{ steps.set-version.outputs.QBEE_TAG }}
          file: ./${{ steps.set-version.outputs.QBEE_TAG }}/nevinee.iyuu.Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: |
            qbitorrent_tag=${{ steps.set-version.outputs.QB_TAG }}
            QBEE_TAG=${{ steps.set-version.outputs.QBEE_TAG }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:${{ steps.set-version.outputs.QB_TAG }}-iyuu
             ${{ secrets.DOCKER_USERNAME }}/qbittorrentee:latest-iyuu

  job1:
    needs: [build1, build2]
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/qbittorrentee
          short-description: 由 nevinee 大佬的 qBittorrent 镜像改编的 qBittorrent Enhanced Edition 镜像
          readme-filepath: ./README.md
