name: Docker readme update

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  job:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Get Description
        id: description
        run: |
          Description=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DDS-Derek/qBittorrent-Enhanced-Edition-Docker | \
            jq -r ".description")
          echo "Description=${Description}"
          echo "Description=${Description}" >> $GITHUB_OUTPUT

      - 
        name: Get dependency version
        id: dependency-version
        run: |
          docker run -d --name=test ddsderek/qbittorrentee:latest
          docker cp test:/usr/bin/dependency-version.json ./dependency-version.json

      -
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore(deps): update dependency version'
          branch: master
          file_pattern: 'dependency-version.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/qbittorrentee
          short-description: ${{ steps.description.outputs.Description }}
          readme-filepath: ./README.md